// GENERATED by `npm run gen:rpc` (scripts/gen-rpc-wrappers.mjs) from src/generated/database.types.ts.
// Do not hand-edit. One wrapper per browser-callable RPC in `public`.
import { callRpc, schoolRpc, type RpcArgs, type RpcOptions, type SchoolArgs } from './client';

export const activateTimetable = (args: SchoolArgs<'activate_timetable'>, options?: RpcOptions) =>
  schoolRpc('activate_timetable', args, options);
export const addInvoiceAdjustment = (args: SchoolArgs<'add_invoice_adjustment'>, options?: RpcOptions) =>
  schoolRpc('add_invoice_adjustment', args, options);
export const admitStudent = (args: SchoolArgs<'admit_student'>, options?: RpcOptions) =>
  schoolRpc('admit_student', args, options);
export const assignSubstitute = (args: SchoolArgs<'assign_substitute'>, options?: RpcOptions) =>
  schoolRpc('assign_substitute', args, options);
export const bootstrapAccount = (args: RpcArgs<'bootstrap_account'> = {}, options?: RpcOptions) =>
  callRpc('bootstrap_account', args, options);
export const bounceCheque = (args: SchoolArgs<'bounce_cheque'>, options?: RpcOptions) =>
  schoolRpc('bounce_cheque', args, options);
export const cancelPaidLeave = (args: SchoolArgs<'cancel_paid_leave'>, options?: RpcOptions) =>
  schoolRpc('cancel_paid_leave', args, options);
export const clearCheque = (args: SchoolArgs<'clear_cheque'>, options?: RpcOptions) =>
  schoolRpc('clear_cheque', args, options);
export const copyTimetable = (args: SchoolArgs<'copy_timetable'>, options?: RpcOptions) =>
  schoolRpc('copy_timetable', args, options);
export const disableMembership = (args: SchoolArgs<'disable_membership'>, options?: RpcOptions) =>
  schoolRpc('disable_membership', args, options);
export const endAppSession = (options?: RpcOptions) => callRpc('end_app_session', undefined, options);
export const endTeachingAssignment = (args: SchoolArgs<'end_teaching_assignment'>, options?: RpcOptions) =>
  schoolRpc('end_teaching_assignment', args, options);
export const evaluateLateFees = (args: SchoolArgs<'evaluate_late_fees'>, options?: RpcOptions) =>
  schoolRpc('evaluate_late_fees', args, options);
export const generateLessonSessions = (args: SchoolArgs<'generate_lesson_sessions'>, options?: RpcOptions) =>
  schoolRpc('generate_lesson_sessions', args, options);
export const getAttendanceOverview = (args: SchoolArgs<'get_attendance_overview'>, options?: RpcOptions) =>
  schoolRpc('get_attendance_overview', args, options);
export const getCollectionReport = (args: SchoolArgs<'get_collection_report'>, options?: RpcOptions) =>
  schoolRpc('get_collection_report', args, options);
export const getContext = (options?: RpcOptions) => callRpc('get_context', undefined, options);
export const getDateSchedule = (args: SchoolArgs<'get_date_schedule'>, options?: RpcOptions) =>
  schoolRpc('get_date_schedule', args, options);
export const getDuesReport = (args: SchoolArgs<'get_dues_report'> = {}, options?: RpcOptions) =>
  schoolRpc('get_dues_report', args, options);
export const getFollowupsDue = (args: SchoolArgs<'get_followups_due'> = {}, options?: RpcOptions) =>
  schoolRpc('get_followups_due', args, options);
export const getHomeworkRoster = (args: SchoolArgs<'get_homework_roster'>, options?: RpcOptions) =>
  schoolRpc('get_homework_roster', args, options);
export const getMarkingRoster = (args: SchoolArgs<'get_marking_roster'>, options?: RpcOptions) =>
  schoolRpc('get_marking_roster', args, options);
export const getReceipt = (args: SchoolArgs<'get_receipt'>, options?: RpcOptions) =>
  schoolRpc('get_receipt', args, options);
export const getSalaryCalculations = (
  args: SchoolArgs<'get_salary_calculations'> = {},
  options?: RpcOptions,
) => schoolRpc('get_salary_calculations', args, options);
export const getSetupSnapshot = (args: SchoolArgs<'get_setup_snapshot'> = {}, options?: RpcOptions) =>
  schoolRpc('get_setup_snapshot', args, options);
export const getStaffConfidential = (args: SchoolArgs<'get_staff_confidential'>, options?: RpcOptions) =>
  schoolRpc('get_staff_confidential', args, options);
export const getStudentAttendanceSummary = (
  args: SchoolArgs<'get_student_attendance_summary'>,
  options?: RpcOptions,
) => schoolRpc('get_student_attendance_summary', args, options);
export const getStudentHomework = (args: SchoolArgs<'get_student_homework'>, options?: RpcOptions) =>
  schoolRpc('get_student_homework', args, options);
export const getStudentProfile = (args: SchoolArgs<'get_student_profile'>, options?: RpcOptions) =>
  schoolRpc('get_student_profile', args, options);
export const getStudentStatement = (args: SchoolArgs<'get_student_statement'>, options?: RpcOptions) =>
  schoolRpc('get_student_statement', args, options);
export const getTeacherToday = (args: SchoolArgs<'get_teacher_today'> = {}, options?: RpcOptions) =>
  schoolRpc('get_teacher_today', args, options);
export const grantConcession = (args: SchoolArgs<'grant_concession'>, options?: RpcOptions) =>
  schoolRpc('grant_concession', args, options);
export const issueOpeningBalance = (args: SchoolArgs<'issue_opening_balance'>, options?: RpcOptions) =>
  schoolRpc('issue_opening_balance', args, options);
export const issueTermInvoices = (args: SchoolArgs<'issue_term_invoices'>, options?: RpcOptions) =>
  schoolRpc('issue_term_invoices', args, options);
export const listLeads = (args: SchoolArgs<'list_leads'> = {}, options?: RpcOptions) =>
  schoolRpc('list_leads', args, options);
export const listStaff = (args: SchoolArgs<'list_staff'> = {}, options?: RpcOptions) =>
  schoolRpc('list_staff', args, options);
export const listStudents = (args: SchoolArgs<'list_students'> = {}, options?: RpcOptions) =>
  schoolRpc('list_students', args, options);
export const markHomeworkChecks = (args: SchoolArgs<'mark_homework_checks'>, options?: RpcOptions) =>
  schoolRpc('mark_homework_checks', args, options);
export const markStaffAttendance = (args: SchoolArgs<'mark_staff_attendance'>, options?: RpcOptions) =>
  schoolRpc('mark_staff_attendance', args, options);
export const markStudentAttendance = (args: SchoolArgs<'mark_student_attendance'>, options?: RpcOptions) =>
  schoolRpc('mark_student_attendance', args, options);
export const movePlacements = (args: SchoolArgs<'move_placements'>, options?: RpcOptions) =>
  schoolRpc('move_placements', args, options);
export const opCreateSchool = (args: RpcArgs<'op_create_school'>, options?: RpcOptions) =>
  callRpc('op_create_school', args, options);
export const opFindAccount = (args: RpcArgs<'op_find_account'>, options?: RpcOptions) =>
  callRpc('op_find_account', args, options);
export const opGetAuditEvents = (args: RpcArgs<'op_get_audit_events'> = {}, options?: RpcOptions) =>
  callRpc('op_get_audit_events', args, options);
export const opGetAuthEvents = (args: RpcArgs<'op_get_auth_events'> = {}, options?: RpcOptions) =>
  callRpc('op_get_auth_events', args, options);
export const opGetUsage = (args: RpcArgs<'op_get_usage'>, options?: RpcOptions) =>
  callRpc('op_get_usage', args, options);
export const opListSchools = (options?: RpcOptions) => callRpc('op_list_schools', undefined, options);
export const opRunRetentionCleanup = (options?: RpcOptions) =>
  callRpc('op_run_retention_cleanup', undefined, options);
export const postCollection = (args: SchoolArgs<'post_collection'>, options?: RpcOptions) =>
  schoolRpc('post_collection', args, options);
export const previewSalary = (args: SchoolArgs<'preview_salary'>, options?: RpcOptions) =>
  schoolRpc('preview_salary', args, options);
export const previewTermInvoices = (args: SchoolArgs<'preview_term_invoices'>, options?: RpcOptions) =>
  schoolRpc('preview_term_invoices', args, options);
export const recordCheque = (args: SchoolArgs<'record_cheque'>, options?: RpcOptions) =>
  schoolRpc('record_cheque', args, options);
export const recordLeadFollowup = (args: SchoolArgs<'record_lead_followup'>, options?: RpcOptions) =>
  schoolRpc('record_lead_followup', args, options);
export const recordPaidLeave = (args: SchoolArgs<'record_paid_leave'>, options?: RpcOptions) =>
  schoolRpc('record_paid_leave', args, options);
export const recordPaymentException = (args: SchoolArgs<'record_payment_exception'>, options?: RpcOptions) =>
  schoolRpc('record_payment_exception', args, options);
export const recordTelemetry = (args: RpcArgs<'record_telemetry'>, options?: RpcOptions) =>
  callRpc('record_telemetry', args, options);
export const removeSubstitute = (args: SchoolArgs<'remove_substitute'>, options?: RpcOptions) =>
  schoolRpc('remove_substitute', args, options);
export const reverseCollection = (args: SchoolArgs<'reverse_collection'>, options?: RpcOptions) =>
  schoolRpc('reverse_collection', args, options);
export const revokeConcession = (args: SchoolArgs<'revoke_concession'>, options?: RpcOptions) =>
  schoolRpc('revoke_concession', args, options);
export const saveAcademicYear = (args: SchoolArgs<'save_academic_year'>, options?: RpcOptions) =>
  schoolRpc('save_academic_year', args, options);
export const saveCalendarPattern = (args: SchoolArgs<'save_calendar_pattern'>, options?: RpcOptions) =>
  schoolRpc('save_calendar_pattern', args, options);
export const saveCalendarRange = (args: SchoolArgs<'save_calendar_range'>, options?: RpcOptions) =>
  schoolRpc('save_calendar_range', args, options);
export const saveClass = (args: SchoolArgs<'save_class'>, options?: RpcOptions) =>
  schoolRpc('save_class', args, options);
export const saveClassSubjects = (args: SchoolArgs<'save_class_subjects'>, options?: RpcOptions) =>
  schoolRpc('save_class_subjects', args, options);
export const saveConcessionPreset = (args: SchoolArgs<'save_concession_preset'>, options?: RpcOptions) =>
  schoolRpc('save_concession_preset', args, options);
export const saveDiaryEntry = (args: SchoolArgs<'save_diary_entry'>, options?: RpcOptions) =>
  schoolRpc('save_diary_entry', args, options);
export const saveFeeHead = (args: SchoolArgs<'save_fee_head'>, options?: RpcOptions) =>
  schoolRpc('save_fee_head', args, options);
export const saveFeeStructure = (args: SchoolArgs<'save_fee_structure'>, options?: RpcOptions) =>
  schoolRpc('save_fee_structure', args, options);
export const saveFeeTerm = (args: SchoolArgs<'save_fee_term'>, options?: RpcOptions) =>
  schoolRpc('save_fee_term', args, options);
export const saveGuardian = (args: SchoolArgs<'save_guardian'>, options?: RpcOptions) =>
  schoolRpc('save_guardian', args, options);
export const saveHomework = (args: SchoolArgs<'save_homework'> = {}, options?: RpcOptions) =>
  schoolRpc('save_homework', args, options);
export const saveLateFeeRule = (args: SchoolArgs<'save_late_fee_rule'>, options?: RpcOptions) =>
  schoolRpc('save_late_fee_rule', args, options);
export const saveLead = (args: SchoolArgs<'save_lead'>, options?: RpcOptions) =>
  schoolRpc('save_lead', args, options);
export const savePeriodSchedule = (args: SchoolArgs<'save_period_schedule'>, options?: RpcOptions) =>
  schoolRpc('save_period_schedule', args, options);
export const saveReceivingAccount = (args: SchoolArgs<'save_receiving_account'>, options?: RpcOptions) =>
  schoolRpc('save_receiving_account', args, options);
export const saveSalaryCalculation = (args: SchoolArgs<'save_salary_calculation'>, options?: RpcOptions) =>
  schoolRpc('save_salary_calculation', args, options);
export const saveSchoolProfile = (args: SchoolArgs<'save_school_profile'>, options?: RpcOptions) =>
  schoolRpc('save_school_profile', args, options);
export const saveSection = (args: SchoolArgs<'save_section'>, options?: RpcOptions) =>
  schoolRpc('save_section', args, options);
export const saveStaff = (args: SchoolArgs<'save_staff'>, options?: RpcOptions) =>
  schoolRpc('save_staff', args, options);
export const saveStaffFinance = (args: SchoolArgs<'save_staff_finance'>, options?: RpcOptions) =>
  schoolRpc('save_staff_finance', args, options);
export const saveStaffGroup = (args: SchoolArgs<'save_staff_group'>, options?: RpcOptions) =>
  schoolRpc('save_staff_group', args, options);
export const saveStudentSensitive = (args: SchoolArgs<'save_student_sensitive'>, options?: RpcOptions) =>
  schoolRpc('save_student_sensitive', args, options);
export const saveSubject = (args: SchoolArgs<'save_subject'>, options?: RpcOptions) =>
  schoolRpc('save_subject', args, options);
export const saveTeachingAssignment = (args: SchoolArgs<'save_teaching_assignment'>, options?: RpcOptions) =>
  schoolRpc('save_teaching_assignment', args, options);
export const saveTimetableDraft = (args: SchoolArgs<'save_timetable_draft'>, options?: RpcOptions) =>
  schoolRpc('save_timetable_draft', args, options);
export const selectContext = (args: RpcArgs<'select_context'> = {}, options?: RpcOptions) =>
  callRpc('select_context', args, options);
export const setAttendanceMode = (args: SchoolArgs<'set_attendance_mode'>, options?: RpcOptions) =>
  schoolRpc('set_attendance_mode', args, options);
export const setCurrentYear = (args: SchoolArgs<'set_current_year'>, options?: RpcOptions) =>
  schoolRpc('set_current_year', args, options);
export const setOptionalFee = (args: SchoolArgs<'set_optional_fee'>, options?: RpcOptions) =>
  schoolRpc('set_optional_fee', args, options);
export const suggestSubstitutes = (args: SchoolArgs<'suggest_substitutes'>, options?: RpcOptions) =>
  schoolRpc('suggest_substitutes', args, options);
export const updateLessonSession = (args: SchoolArgs<'update_lesson_session'>, options?: RpcOptions) =>
  schoolRpc('update_lesson_session', args, options);
export const updateStudent = (args: SchoolArgs<'update_student'>, options?: RpcOptions) =>
  schoolRpc('update_student', args, options);
export const waiveLateFee = (args: SchoolArgs<'waive_late_fee'>, options?: RpcOptions) =>
  schoolRpc('waive_late_fee', args, options);

/** RPCs that take p_ctx_rev (81). */
export const SCHOOL_RPCS = [
  'activate_timetable',
  'add_invoice_adjustment',
  'admit_student',
  'assign_substitute',
  'bounce_cheque',
  'cancel_paid_leave',
  'clear_cheque',
  'copy_timetable',
  'disable_membership',
  'end_teaching_assignment',
  'evaluate_late_fees',
  'generate_lesson_sessions',
  'get_attendance_overview',
  'get_collection_report',
  'get_date_schedule',
  'get_dues_report',
  'get_followups_due',
  'get_homework_roster',
  'get_marking_roster',
  'get_receipt',
  'get_salary_calculations',
  'get_setup_snapshot',
  'get_staff_confidential',
  'get_student_attendance_summary',
  'get_student_homework',
  'get_student_profile',
  'get_student_statement',
  'get_teacher_today',
  'grant_concession',
  'issue_opening_balance',
  'issue_term_invoices',
  'list_leads',
  'list_staff',
  'list_students',
  'mark_homework_checks',
  'mark_staff_attendance',
  'mark_student_attendance',
  'move_placements',
  'post_collection',
  'preview_salary',
  'preview_term_invoices',
  'record_cheque',
  'record_lead_followup',
  'record_paid_leave',
  'record_payment_exception',
  'remove_substitute',
  'reverse_collection',
  'revoke_concession',
  'save_academic_year',
  'save_calendar_pattern',
  'save_calendar_range',
  'save_class',
  'save_class_subjects',
  'save_concession_preset',
  'save_diary_entry',
  'save_fee_head',
  'save_fee_structure',
  'save_fee_term',
  'save_guardian',
  'save_homework',
  'save_late_fee_rule',
  'save_lead',
  'save_period_schedule',
  'save_receiving_account',
  'save_salary_calculation',
  'save_school_profile',
  'save_section',
  'save_staff',
  'save_staff_finance',
  'save_staff_group',
  'save_student_sensitive',
  'save_subject',
  'save_teaching_assignment',
  'save_timetable_draft',
  'set_attendance_mode',
  'set_current_year',
  'set_optional_fee',
  'suggest_substitutes',
  'update_lesson_session',
  'update_student',
  'waive_late_fee',
] as const;
/** Browser RPCs without a context revision (12). */
export const CONTEXTLESS_RPCS = [
  'bootstrap_account',
  'end_app_session',
  'get_context',
  'op_create_school',
  'op_find_account',
  'op_get_audit_events',
  'op_get_auth_events',
  'op_get_usage',
  'op_list_schools',
  'op_run_retention_cleanup',
  'record_telemetry',
  'select_context',
] as const;
